version: '2'
services:
  app:
    build: .
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DEBUG=true
    depends_on:
      - database
    ports:
      - 8080:8000
    volumes:
      - ./:/app
  database:
    image: postgres:latest
    environment:
      - FOO=BAR
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/pgsql
