CREATE TABLE IF NOT EXISTS feedback (
    id SERIAL NOT NULL,
    service VARCHAR(255) NOT NULL,
    edition VARCHAR(255) NOT NULL,
    text TEXT NOT NULL,
    extra JSONB,
    created_at INTEGER NOT NULL DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP),
    updated_at INTEGER NOT NULL DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP),
    PRIMARY KEY (id)
);
